# Auto-generated from Contingency_Business_Processes_vs_Products.xlsx.
# 150 Business Applications (products) + business processes, plus a
# contingency map linking product -> process / failed system / owner.

PRODUCTS = [
    {'name': 'Cloud Security', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Cyber Threat Detection', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Cyber Threat Exposure Management', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Cyber Threat Hunting', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Cyber Threat Intelligence', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Email Security', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Endpoint Security', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Identity Security', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Network Security', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'OT Secure Remote Access', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Privacy Management', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'Security Monitoring', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'iGRC', 'platform': 'Cybersecurity & Data Privacy'},
    {'name': 'BDAA Demand Forecasting', 'platform': 'Data, Insights and AI'},
    {'name': 'Big Data Platform - BW', 'platform': 'Data, Insights and AI'},
    {'name': 'Big Data Platform - Data Mesh', 'platform': 'Data, Insights and AI'},
    {'name': 'GenAI Incubator', 'platform': 'Data, Insights and AI'},
    {'name': 'Logistics Value 360', 'platform': 'Data, Insights and AI'},
    {'name': 'Master Data Diagnosis and Profiling', 'platform': 'Data, Insights and AI'},
    {'name': 'Master Data Platform - Customer and Vendor', 'platform': 'Data, Insights and AI'},
    {'name': 'PAAT', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting Commercial', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting Cross Functional', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting Edge', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting Factory Services', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting Finance', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting People & Culture', 'platform': 'Data, Insights and AI'},
    {'name': 'Reporting Supply Chain', 'platform': 'Data, Insights and AI'},
    {'name': 'Segmented Execution', 'platform': 'Data, Insights and AI'},
    {'name': 'Segmented Execution (Digital Channels)', 'platform': 'Data, Insights and AI'},
    {'name': 'brAInBank', 'platform': 'Data, Insights and AI'},
    {'name': 'Autonomous Retail', 'platform': 'Digital Consumer & Customer'},
    {'name': 'B2B & D2C Customer Portal for EG', 'platform': 'Digital Consumer & Customer'},
    {'name': 'CAM (Customer Assets Management)', 'platform': 'Digital Consumer & Customer'},
    {'name': 'CCH Customer Portal', 'platform': 'Digital Consumer & Customer'},
    {'name': 'ComPol Tool', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Commercial CMS', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Commercial Collaboration Space', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Connected Drinks Equipment', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Contact Center', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Customer Interaction Centre', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Customer Planning Tool', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Customer Simulation Tool (CST)', 'platform': 'Digital Consumer & Customer'},
    {'name': 'D365 Activity Management', 'platform': 'Digital Consumer & Customer'},
    {'name': 'D365 Customer Care Center', 'platform': 'Digital Consumer & Customer'},
    {'name': 'D365 RED', 'platform': 'Digital Consumer & Customer'},
    {'name': 'D365 Technology', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Dynamic Routing', 'platform': 'Digital Consumer & Customer'},
    {'name': 'EDI/VMI', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Integrated Order Management (IOM)', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Lead to Customer', 'platform': 'Digital Consumer & Customer'},
    {'name': 'MITme', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Marketing Cloud', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Pay for Performance (PfP) Tool', 'platform': 'Digital Consumer & Customer'},
    {'name': 'RED IR', 'platform': 'Digital Consumer & Customer'},
    {'name': 'RGM Toolkit', 'platform': 'Digital Consumer & Customer'},
    {'name': 'SDO (Indirect Data sharing solution)', 'platform': 'Digital Consumer & Customer'},
    {'name': 'SFA', 'platform': 'Digital Consumer & Customer'},
    {'name': 'SFA Lite', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Sales Academy Metaverse', 'platform': 'Digital Consumer & Customer'},
    {'name': 'SalesBuzz (Egypt)', 'platform': 'Digital Consumer & Customer'},
    {'name': 'SelfRED', 'platform': 'Digital Consumer & Customer'},
    {'name': 'TPM', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Valser Service', 'platform': 'Digital Consumer & Customer'},
    {'name': 'eRED for FSA', 'platform': 'Digital Consumer & Customer'},
    {'name': 'Digital Onboarding', 'platform': 'Digital Employee'},
    {'name': 'Employee Experience Platform', 'platform': 'Digital Employee'},
    {'name': 'Historical HR Core& Absence management', 'platform': 'Digital Employee'},
    {'name': 'Intranet', 'platform': 'Digital Employee'},
    {'name': 'Learning & Digital Coaching', 'platform': 'Digital Employee'},
    {'name': 'New HR Core', 'platform': 'Digital Employee'},
    {'name': 'Payroll', 'platform': 'Digital Employee'},
    {'name': 'Performance Management', 'platform': 'Digital Employee'},
    {'name': 'Publishing & Stakeholders Engagement', 'platform': 'Digital Employee'},
    {'name': 'Rewards & Incentives', 'platform': 'Digital Employee'},
    {'name': 'Talent Acquisition', 'platform': 'Digital Employee'},
    {'name': 'Talent Management', 'platform': 'Digital Employee'},
    {'name': 'Time & Attendance', 'platform': 'Digital Employee'},
    {'name': '3rd Party Due Diligence', 'platform': 'Digital Enterprise'},
    {'name': 'AP Invoice Process Management', 'platform': 'Digital Enterprise'},
    {'name': 'BDAA Manufacturing Digital Twin', 'platform': 'Digital Enterprise'},
    {'name': 'Balance Sheet Reconciliation', 'platform': 'Digital Enterprise'},
    {'name': 'COBC& Anti-bribery tool', 'platform': 'Digital Enterprise'},
    {'name': 'Cash Application & Account Receivables', 'platform': 'Digital Enterprise'},
    {'name': 'Collection & Dispute Management', 'platform': 'Digital Enterprise'},
    {'name': 'Concentrate Incidence', 'platform': 'Digital Enterprise'},
    {'name': 'Connected Worker/Digital Shopfloor', 'platform': 'Digital Enterprise'},
    {'name': 'Consolidation (BPC, Disclosure management, Front)', 'platform': 'Digital Enterprise'},
    {'name': 'Controlling', 'platform': 'Digital Enterprise'},
    {'name': 'Corporate Audit and Control', 'platform': 'Digital Enterprise'},
    {'name': 'Credit & Credit Granting Management', 'platform': 'Digital Enterprise'},
    {'name': 'Customer Billing & Invoicing', 'platform': 'Digital Enterprise'},
    {'name': 'Customer Collaboration Planning', 'platform': 'Digital Enterprise'},
    {'name': 'E2E Connected Enterprise Planning', 'platform': 'Digital Enterprise'},
    {'name': 'Finance closing cockpit', 'platform': 'Digital Enterprise'},
    {'name': 'Financial & Assets Accounting', 'platform': 'Digital Enterprise'},
    {'name': 'HO Treasury Solutions', 'platform': 'Digital Enterprise'},
    {'name': 'Integrated Business Planning (BPS)', 'platform': 'Digital Enterprise'},
    {'name': 'Integrated CAPEX Management (COIN)', 'platform': 'Digital Enterprise'},
    {'name': 'Intercompany Services Recharges', 'platform': 'Digital Enterprise'},
    {'name': 'Lease accounting (Planon)', 'platform': 'Digital Enterprise'},
    {'name': 'Manufacturing IIoT Platform', 'platform': 'Digital Enterprise'},
    {'name': 'Mobile Maintenance', 'platform': 'Digital Enterprise'},
    {'name': 'OPEX Planning DB (CSC)', 'platform': 'Digital Enterprise'},
    {'name': 'Opex & Profitability allocation', 'platform': 'Digital Enterprise'},
    {'name': 'Outgoing Payment Management', 'platform': 'Digital Enterprise'},
    {'name': 'Plant Maintenance', 'platform': 'Digital Enterprise'},
    {'name': 'Pricing Management', 'platform': 'Digital Enterprise'},
    {'name': 'Procurement Sourcing and Contracting', 'platform': 'Digital Enterprise'},
    {'name': 'Procurement Spend and Categorization Insights', 'platform': 'Digital Enterprise'},
    {'name': 'Procurement Supplier Insights', 'platform': 'Digital Enterprise'},
    {'name': 'Product Quality Monitoring', 'platform': 'Digital Enterprise'},
    {'name': 'Production Operations', 'platform': 'Digital Enterprise'},
    {'name': 'Purchase Management', 'platform': 'Digital Enterprise'},
    {'name': 'Quality Audit Management', 'platform': 'Digital Enterprise'},
    {'name': 'Raw Materials Management', 'platform': 'Digital Enterprise'},
    {'name': 'Route Settlement', 'platform': 'Digital Enterprise'},
    {'name': 'Shared Service Framework', 'platform': 'Digital Enterprise'},
    {'name': 'Supply Planning Platform', 'platform': 'Digital Enterprise'},
    {'name': 'Tax & Compliance', 'platform': 'Digital Enterprise'},
    {'name': 'Track & Trace', 'platform': 'Digital Enterprise'},
    {'name': 'Transfer Pricing and Reporting', 'platform': 'Digital Enterprise'},
    {'name': 'Transportation Management System (TMS)', 'platform': 'Digital Enterprise'},
    {'name': 'Travel & Expenses Management', 'platform': 'Digital Enterprise'},
    {'name': 'Warehouse Management System (WMS)', 'platform': 'Digital Enterprise'},
    {'name': 'Warehouse Management System (WMS) - Mobile', 'platform': 'Digital Enterprise'},
    {'name': 'Access Compliance', 'platform': 'Enabling Technology'},
    {'name': 'Agile Collaboration', 'platform': 'Enabling Technology'},
    {'name': 'Authorization Roles Management', 'platform': 'Enabling Technology'},
    {'name': 'Business Connectivity Services', 'platform': 'Enabling Technology'},
    {'name': 'Cloud Services', 'platform': 'Enabling Technology'},
    {'name': 'Collaboration and Productivity', 'platform': 'Enabling Technology'},
    {'name': 'Customer & Employee Voice Services', 'platform': 'Enabling Technology'},
    {'name': 'Digital Service Intelligence', 'platform': 'Enabling Technology'},
    {'name': 'Digital Service Modelling', 'platform': 'Enabling Technology'},
    {'name': 'Directory services', 'platform': 'Enabling Technology'},
    {'name': 'Employee Device Management', 'platform': 'Enabling Technology'},
    {'name': 'Enterprise Resource Planning', 'platform': 'Enabling Technology'},
    {'name': 'Enterprise Service Management', 'platform': 'Enabling Technology'},
    {'name': 'IAM Support Services', 'platform': 'Enabling Technology'},
    {'name': 'IT Service Management', 'platform': 'Enabling Technology'},
    {'name': 'Identity Access Management', 'platform': 'Enabling Technology'},
    {'name': 'Mobile Services', 'platform': 'Enabling Technology'},
    {'name': 'Printing Services', 'platform': 'Enabling Technology'},
    {'name': 'Reporting and Recharging', 'platform': 'Enabling Technology'},
    {'name': 'Service Management Tools', 'platform': 'Enabling Technology'},
    {'name': 'SmartPMO', 'platform': 'Tech Strategy & Operations'},
    {'name': 'Integration Framework', 'platform': 'Z Digital Factories'},
    {'name': 'MS Application Services', 'platform': 'Z Digital Factories'},
    {'name': 'Robotic Process Automation', 'platform': 'Z Digital Factories'},
]

BUSINESS_PROCESSES = [
    'Transfer indirect orders from SFA to SDO',
    'Upload BD orders into ERP',
    'Business Developers take orders offline',
    'BDs place orders via Call Center',
    'Business Developers take orders offline (Egypt)',
    'Delivery execution on paper (Egypt)',
    'Order taking in Excel',
    'Order taking in D365',
    'Manage inbound & outbound calls',
    'EDI order processing',
    'Dynamic transportation planning (dispatching)',
    'Delivery execution on paper for DSD & FSV shipments',
    'Manual release of orders',
    'CDO breakdown service & preventive maintenance',
    'Create promotions in CRM TPM',
    'Collaboration between BSO and countries',
    'Access Fiori applications',
    'Access BW via Analysis for Excel',
    'Incident & service request management',
    'Enterprise service management',
    'Robotic process automation',
    'User access & governance',
    'Material master data maintenance',
    'FI master data maintenance',
    'Customer management',
    'Vendor management',
    'Production execution',
    'Warehouse picking',
    'Create production, purchase & stock transport orders in ERP',
    'Access month-end closing reports in ERP',
    'Execute period-end closing in ERP',
    'Treasury rates management',
    'Financial planning',
    'Post AP invoices in ERP',
    'Fiscal document printing (Bosnia)',
    'Fiscal document printing (Bulgaria)',
]

CONTINGENCY_MAP = [
    {'product': 'SDO (Indirect Data sharing solution)', 'process': 'Transfer indirect orders from SFA to SDO', 'failed_system': 'CRM, PO', 'owner': 'Svetlana Lada'},
    {'product': 'Integrated Order Management (IOM)', 'process': 'Upload BD orders into ERP', 'failed_system': 'CRM', 'owner': 'Svetlana Lada'},
    {'product': 'SFA', 'process': 'Business Developers take orders offline', 'failed_system': 'SFA', 'owner': 'Svetlana Lada'},
    {'product': 'SFA', 'process': 'BDs place orders via Call Center', 'failed_system': 'SFA', 'owner': 'Svetlana Lada'},
    {'product': 'SalesBuzz (Egypt)', 'process': 'Business Developers take orders offline (Egypt)', 'failed_system': 'SBz', 'owner': 'Ahmed Awad Mohamed'},
    {'product': 'SalesBuzz (Egypt)', 'process': 'Delivery execution on paper (Egypt)', 'failed_system': 'SBz', 'owner': 'Ahmed Awad Mohamed'},
    {'product': 'Integrated Order Management (IOM)', 'process': 'Order taking in Excel', 'failed_system': 'ERP, CRM', 'owner': 'Maxwell Odigie'},
    {'product': 'D365 Customer Care Center', 'process': 'Order taking in D365', 'failed_system': 'D365', 'owner': 'Dimitris Alevizopoulos'},
    {'product': 'Contact Center', 'process': 'Manage inbound & outbound calls', 'failed_system': 'CTI', 'owner': 'Lachezar Gavrilov'},
    {'product': 'EDI/VMI', 'process': 'EDI order processing', 'failed_system': 'EDI', 'owner': 'Svetlana Lada'},
    {'product': 'Dynamic Routing', 'process': 'Dynamic transportation planning (dispatching)', 'failed_system': 'LEO', 'owner': 'Cvetanka Ilkova'},
    {'product': 'Route Settlement', 'process': 'Delivery execution on paper for DSD & FSV shipments', 'failed_system': 'P44, P45, Movilizer', 'owner': 'Svetla Petrova'},
    {'product': 'Credit & Credit Granting Management', 'process': 'Manual release of orders', 'failed_system': 'EBS', 'owner': 'Stefan Pavlov'},
    {'product': 'CAM (Customer Assets Management)', 'process': 'CDO breakdown service & preventive maintenance', 'failed_system': 'Movilizer Cloud', 'owner': 'Stoian Chilikov'},
    {'product': 'TPM', 'process': 'Create promotions in CRM TPM', 'failed_system': 'XTEL', 'owner': 'Tsvetan Nikolov'},
    {'product': 'Shared Service Framework', 'process': 'Collaboration between BSO and countries', 'failed_system': 'SSF', 'owner': 'Stefan Pavlov'},
    {'product': 'Enterprise Resource Planning', 'process': 'Access Fiori applications', 'failed_system': 'Fiori', 'owner': 'Nikolay Nikolaev'},
    {'product': 'Big Data Platform - BW', 'process': 'Access BW via Analysis for Excel', 'failed_system': 'Fiori', 'owner': 'Dragoljub Popovic'},
    {'product': 'IT Service Management', 'process': 'Incident & service request management', 'failed_system': 'ServiceNow', 'owner': 'Vanya Zdravkova'},
    {'product': 'Enterprise Service Management', 'process': 'Enterprise service management', 'failed_system': 'ServiceNow', 'owner': 'Polina Gyoreva / Stefan Pavlov'},
    {'product': 'Robotic Process Automation', 'process': 'Robotic process automation', 'failed_system': 'RPA', 'owner': 'Viktor Larkov'},
    {'product': 'Identity Access Management', 'process': 'User access & governance', 'failed_system': 'MyID', 'owner': 'Liliya Toncheva'},
    {'product': 'Master Data Platform - Customer and Vendor', 'process': 'Customer management', 'failed_system': 'Winshuttle, Fiori', 'owner': 'Valentyna Bovsunovska'},
    {'product': 'Master Data Platform - Customer and Vendor', 'process': 'Vendor management', 'failed_system': 'MDG', 'owner': 'Valentyna Bovsunovska'},
    {'product': 'Master Data Platform - Customer and Vendor', 'process': 'Customer management', 'failed_system': 'CDC, Winshuttle', 'owner': 'Georgi Velichkov / Valentyna Bovsunovska / Dimitris Alevizopoulos'},
    {'product': 'Master Data Platform - Customer and Vendor', 'process': 'Customer management', 'failed_system': 'CDC_MDG', 'owner': 'Georgi Velichkov / Valentyna Bovsunovska / Dimitris Alevizopoulos'},
    {'product': 'Production Operations', 'process': 'Production execution', 'failed_system': 'MES, ERP, P66', 'owner': 'Ioannis Manolopoulos'},
    {'product': 'Production Operations', 'process': 'Production execution', 'failed_system': 'LTS, ERP, P66', 'owner': 'Ioannis Manolopoulos'},
    {'product': 'Warehouse Management System (WMS) - Mobile', 'process': 'Warehouse picking', 'failed_system': 'Vision Picking', 'owner': 'Julie Aristodemou'},
    {'product': 'Supply Planning Platform', 'process': 'Create production, purchase & stock transport orders in ERP', 'failed_system': 'APO', 'owner': 'Janet Markova'},
    {'product': 'Big Data Platform - BW', 'process': 'Access month-end closing reports in ERP', 'failed_system': 'BW', 'owner': 'Anne Melder / Evangelos Geronikolos'},
    {'product': 'Finance closing cockpit', 'process': 'Execute period-end closing in ERP', 'failed_system': 'Financial Closing Cockpit', 'owner': 'Anne Melder'},
    {'product': 'HO Treasury Solutions', 'process': 'Treasury rates management', 'failed_system': 'Bloomberg Interface, ARE Rates', 'owner': 'Nicolae Butnar'},
    {'product': 'E2E Connected Enterprise Planning', 'process': 'Financial planning', 'failed_system': 'W2 EP', 'owner': 'Francesca Ditta'},
    {'product': 'AP Invoice Process Management', 'process': 'Post AP invoices in ERP', 'failed_system': 'FIP', 'owner': 'Nikos Machlas'},
    {'product': 'Tax & Compliance', 'process': 'Fiscal document printing (Bosnia)', 'failed_system': 'TRING', 'owner': 'Svetla Petrova'},
    {'product': 'Tax & Compliance', 'process': 'Fiscal document printing (Bulgaria)', 'failed_system': 'IASUTD', 'owner': 'Svetla Petrova'},
]
